<?php
echo "
<tr>
<td>1</td><td>1</td><td>1</td><td>1</td><td>1</td>
</tr>
<tr>
<td>1</td><td>2</td><td>1</td><td>1</td><td>1</td>
</tr><tr>
<td>1</td><td>2</td><td>1</td><td>1</td><td>1</td>
</tr><tr>
<td>1</td><td>6847</td><td>1</td><td>1</td><td>1</td>
</tr><tr>
<td>1</td><td>545</td><td>1</td><td>1</td><td>1</td>
</tr><tr>
<td>1</td><td>4545</td><td>1</td><td>1</td><td>1</td>
</tr><tr>
<td>1</td><td>545</td><td>1</td><td>1</td><td>1</td>
</tr><tr>
<td>1</td><td>86</td><td>1</td><td>1</td><td>1</td>
</tr><tr>
<td>1</td><td>1</td><td>1</td><td>1</td><td>1</td>
</tr><tr>
<td>1</td><td>1</td><td>1</td><td>1</td><td>1</td>
</tr><tr>
<td>1</td><td>1</td><td>1</td><td>1</td><td>1</td>
</tr><tr>
<td>1</td><td>1</td><td>1</td><td>1</td><td>1</td>
</tr><tr>
<td>1</td><td>1</td><td>1</td><td>1</td><td>1</td>
</tr><tr>
<td>1</td><td>1</td><td>1</td><td>1</td><td>1</td>
</tr><tr>
<td>1</td><td>1</td><td>1</td><td>1</td><td>1</td>
</tr>";

?>